---
# Source: dbinit/templates/dbinit.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: dbinit
spec:
  template:
    spec:
      containers:
      - env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: events-secret
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: events-secret
        envFrom:
          - configMapRef:
              name: events
        name: dbinit
        image: jamesrelph/events-dbinit:latest
        volumeMounts:
          - mountPath: /events-secret
            name: events-secret
            readOnly: true
      serviceAccountName: secrets-manager-account
      volumes:
        - csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: events-spc
          name: events-secret
      restartPolicy: Never
  backoffLimit: 4
