apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: events-spc
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "eventsDb"
        objectType: "secretsmanager"
        jmesPath:
          - path: dbUser
            objectAlias: username
          - path: dbPassword
            objectAlias: password
          - path: dbName
            objectAlias: name
    usePodIdentity: "true"
  secretObjects:
    - secretName: events-secret
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
        - objectName: name
          key: name
  
