apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: burstable
spec:
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: burstable

      requirements:
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["t"]
        - key: "eks.amazonaws.com/instance-cpu"
          operator: In
          values: ["1", "2", "4", "8"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["eu-west-2a", "eu-west-2b", eu-west-2c]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]

  limits:
    cpu: "1000"
    memory: 1000Gi
