apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: burstable
spec:
  role: {{ .Values.nodeIamRoleName }}
  subnetSelectorTerms:
    - tags:
        cluster: {{ .Values.clusterName }}
  securityGroupSelectorTerms:
    - tags:
        cluster: {{ .Values.clusterName }}
  ephemeralStorage:
    size: "80Gi"    # Range: 1-9000Gi or 1-64000G or 1-58Ti or 1-64T
    iops: 3000      # Range: 3000-16000
    throughput: 125 # Range: 125-1000
  networkPolicy: DefaultAllow
  networkPolicyEventLogs: Disabled
  snatPolicy: Random