apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: events-api
  name: events-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-api
  template:
    metadata:
      labels:
        app: events-api
    spec:
      containers:
      - image: jamesrelph/events-api
        name: events-api
        ports:
        - containerPort: 8082
        env:
        - name: DBHOST
          value: {{ .Values.globalEndpoint }}
        - name: DBUSER
          value: {{ .Values.dbUser }}
        - name: DBPASSWORD
          value: {{ .Values.dbPassword }}
        - name: DBDATABASE
          value: {{ .Values.dbName }}
