apiVersion: batch/v1
kind: Job
metadata:
  name: dbinit
spec:
  template:
    spec:
      containers:
      - name: dbinit
        image: jamesrelph/events-dbinit:latest
      - env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: events-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: events-secret
        envFrom:
        - configMapRef:
            name: events
      restartPolicy: Never
  backoffLimit: 4