apiVersion: batch/v1
kind: Job
metadata:
  name: dbinit
spec:
  template:
    spec:
      containers:
      - env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: events-secret
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: events-secret
        name: dbinit
        image: jamesrelph/events-dbinit:latest
      serviceAccountName: secrets-manager-account
      restartPolicy: Never
  backoffLimit: 4