apiVersion: batch/v1
kind: Job
metadata:
  name: dbinit
spec:
  template:
    spec:
      containers:
      - name: dbinit
        image: jamesrelph/events-dbinit:latest
        env:
          - name: DBHOST
            value: {{ .Values.globalEndpoint }}
          - name: DBUSER
            value: {{ .Values.dbUser }}
          - name: DBPASSWORD
            value: {{ .Values.dbPassword }}
          - name: DBDATABASE
            value: {{ .Values.dbName }}
      restartPolicy: Never
  backoffLimit: 4