name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Website
      working-directory: ./eventsapp/events-website
      run: docker build . --tag jamesrelph/events-website:$(date +%s)
    - name: Build API
      working-directory: ./eventsapp/events-api
      run: docker build . --tag jamesrelph/events-api:$(date +%s)
    - name: Build DBInit
      working-directory: ./eventsapp/events-dbinit
      run: docker build . --tag jamesrelph/events-dbinit:$(date +%s)
