name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TAG: $(date +%s)

jobs:

  build:

    runs-on: ubuntu-latest
    environment: Prod

    steps:
    - uses: actions/checkout@v4

    - name: Docker Hub login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
       
    - name: Build Website
      working-directory: ./eventsapp/events-website
      run: |
        docker build . --tag jamesrelph/events-website:$TAG
        docker push jamesrelph/events-website:$TAG

    - name: Build API
      working-directory: ./eventsapp/events-api
      run: |
        docker build . --tag jamesrelph/events-api:$TAG
        docker push jamesrelph/events-api:$TAG
        
    - name: Build DBInit
      working-directory: ./eventsapp/events-dbinit
      run: |
        docker build . --tag jamesrelph/events-dbinit:$TAG
        docker push jamesrelph/events-dbinit:$TAG
