name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file eventsapp/events-website/Dockerfile --tag jamesrelph/events-website:$(date +%s)
           docker build . --file eventsapp/events-api/Dockerfile --tag jamesrelph/events-api:$(date +%s)
           docker build . --file eventsapp/events-dbinit/Dockerfile --tag jamesrelph/events-dbinit:$(date +%s)
