name: EKS Control

on:
  workflow_dispatch:
    inputs:
      AWS_REGION:
        description: "AWS Region"
        required: true
        default: "us-east-1"
        type: choice
        options:
          - us-east-1
          - us-east-2
      CLUSTER_NAME:
        description: "Cluster Name"
        required: true
        type: string

      EKS_ACTION:
        description: "EKS Action"
        required: true
        default: "create"
        type: choice
        options:
          - create
          - destroy
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
    - uses: actions/checkout@v4

    - name: Login to AWS
      uses: aws-actions/configure-aws-credentials@v4.2.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION}}

    - name: Create EKS Cluster
      working-directory: ./aws
      run: |
           ARCH=amd64
           PLATFORM=$(uname -s)_$ARCH
           curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
           curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check
           tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
           sudo install -m 0755 /tmp/eksctl /usr/local/bin && rm /tmp/eksctl
           eksctl ${{ inputs.EKS_ACTION }} cluster --name ${{ inputs.CLUSTER_NAME }} --region ${{ inputs.AWS_REGION}} -f cluster.yaml
