name: Helm Build
on:
  push:
    paths:
      - helm/**
    branches: [ "main" ]
  pull_request:
    paths:
      - helm/**
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Prod

    steps:
    - uses: actions/checkout@v4

    - name: Docker Hub login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
      
    - name: Package Helm Chart
      working-directory: ./helm
      run: |
        helm package ./events 

    - name: Push Helm Chart
      working-directory: ./helm
      run: |
        version = $(helm show chart ./events | grep -E "^version:" | awk '{print $2}')
        helm push events-$version.tgz oci://registry-1.docker.io/jamesrelph
