name: Secrets Test

on:
  workflow_dispatch:
    inputs:
      Secrets Test:
        description: "Test SM Action"
        required: true
        default: "test"
        type: choice
        options:
          - test

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
    - uses: actions/checkout@v4
    - name: AWS Login
      uses: aws-actions/configure-aws-credentials@v4.2.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    
    - name: Get secrets by name and by ARN
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
      secret-ids: |
        ,eventsDb
    - name: Test
      run: echo "$dbUSer $dbPassword $dbName"